#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# OpenFOAM functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
solver=`getApplication`

# Generate mesh
#/usr/bin/gmsh -3 bendingColumnFluid.geo -o bendingColumnFluid.msh > log.gmsh
gmshToFoam bendingColumnFluid.msh > log.gmshToFoam

# Run solver
$solver > log.$solver &
tail -f log.$solver
