#!/bin/bash

printf "\n\n........................................\n"
printf '\e[1;34m%-6s\e[m' "Compiling mathematics_vc module"
printf "\n........................................\n\n"

wclean libso && wmake -update -j libso
