#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# OpenFOAM functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
solver=`getApplication`

# Generate mesh
meshFile=$(grep '^meshFile.*;$' constant/runParameters | sed -e 's/meshFile\(.*\);/\1/')
gmshToFoam $meshFile
	
#initial solution
initialConditions_vcALE

# Run solver
#$solver
vcALEFoam > log.$solver &
tail -f log.$solver
