#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# OpenFOAM functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
solver=`getApplication`

# Generate mesh
meshFile=$(grep '^meshFile.*;$' constant/runParameters | sed -e 's/meshFile\(.*\);/\1/')
/usr/bin/gmsh -3 bendingColumn.geo -o $meshFile > log.gmsh
gmshToFoam $meshFile


initialConditions_vcALE > log.initialConditions_vcALE

# Run solver
$solver > log.$solver &
tail -f log.$solver
