#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase;
rm -rf *.png 0/p 0/u 0/E 0/matJ 0/uw 0/v_ log.* *.jpeg;
#killall vcALEFoam

#/usr/bin/gmsh -3 bendingColumn.geo -o bendingColumn_625.msh > log.gmsh
#gmshToFoam bendingColumn_625.msh > log.gmshToFoam

echo Case Cleaned!
