#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase;
rm *.png 0/p 0/u;

gmsh -3 bendingColumn.geo -o bendingColumn_625.msh > log.gmsh
gmshToFoam bendingColumn_625.msh > log.gmshToFoam

echo Case Cleaned!
