#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# OpenFOAM functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
solver=`getApplication`

# Generate mesh
#/usr/bin/gmsh -3 bendingColumn.geo -o bendingColumn_625.msh > log.gmsh
meshFile=$(grep '^meshFile.*;$' constant/runParameters | sed -e 's/meshFile\(.*\);/\1/')
gmshToFoam $meshFile > log.gmshToFoam
	
# Initial solution
initialConditions_vcALE  > log.initialConditions_vcALE

# Decompost Solution
#runApplication decomposePar

# Run solver
$solver > log.$solver &
#tail -f log.$solver
